### ISSUE TITLE
Question: Configuration to Celery Worker

### ISSUE THREAD

**Issue by rathish** [selinon/selinon#136]
## Issue description:
Hello,

it might be stupid question, since we are not able to achieve the functionalities I am raising this question.

We have designed DAG automation within our Django Project, for that we have developed a DAG designer in React with minimal set of nodes, and planning to use Selinon / Celery to run the workflow. Problem we are facing is transporting the configuration with Django server and Celery.

Below is our execution flow
[ API ] =>  [ Django Signal ] => [ Handler ] => [ Identify the Workflow ] => [ Convert the flow to Selinon Understanding Dict ] => [ Run Flow ] =>  [ Celery Task Execution ]

We are able to achieve up-to the Run Flow step, when we run Config is not passed to Celery (note: we have Celery process to run different tasks running along with Django project).

We understand Selinon Config class is not Singleton and Celery is loading the Class and missing the Dispatcher Queue configuration which set in the main process which initiated in the Django Server. 

Not sure whether we are using Selinon or Celery correctly, any direction will help to complete out usecase.   

### Links to logs:

A link to logs posted on http://pastebin.com/ (or any other publicly reachable service).

### Selinon & Celery version:

Running `selinon-cli version` gave me:

- [ ] I have tried the latest master but the issue still pesists:
  `pip3 install --force-reinstall git+https://github.com/selinon/selinon@master`

**Comment by rathish** [comment]
Hi fridex, 

We referred your demo worker project and tried like below.

`def send_selinon(request):
    app = Celery('app')
    conf = {
        'broker_url': settings.CELERY_BROKER_URL,
        'result_backend' : settings.CELERY_RESULT_BACKEND,
    }

    app.config_from_object(conf)
    node_dict = {
        'tasks': [{'name': 'CheckMessage', 'queue': 'hello_task', 'import': 'tasks', 'max_retry':0, 'storage': 'Redis'},
                 {'name': 'MessageLength', 'queue': 'hello_task', 'import': 'tasks', 'max_retry':0, 'storage': 'Redis'},
                 {'name': 'SuccessAction', 'queue': 'hello_task', 'import': 'tasks', 'max_retry':0, 'storage': 'Redis'},
                 {'name': 'FailureAction', 'queue': 'hello_task', 'import': 'tasks', 'max_retry':0, 'storage': 'Redis'}],
         'flows': ['my_new_flow'],
         'storages': [{'name': 'Redis', 'import': 'selinon.storages.redis', 'configuration': {'host': 'localhost', 'port':6379, 'db':1, 'charset': 'utf-8'}}],
         'global': {'trace': {'json': True}},
         'migration_dir': 'migration_dir'}

    flow_definition = [{'flow-definitions': [{'name': 'my_new_flow',
                                              'queue': 'hello_task',
                                              'sampling': {'name': 'constant', 'args': {'retry': 10}},
                                              'edges': [{'from': '', 'to': 'CheckMessage'},
                                                        {'from': 'CheckMessage', 'to': 'MessageLength'},
                                                        {'from': 'MessageLength', 'to': 'SuccessAction', 
                                                         'condition': {'name': 'fieldEqual',
                                                                       'args': {'key': 'status', 'value': True}}},
                                                        {'from': 'MessageLength', 'to': 'FailureAction',
                                                         'condition': {'name': 'fieldEqual',
                                                                       'args': {'key': 'status', 'value': False}}}],
                                              'failures': [{'nodes': 'MessageLength', 'fallback': 'FailureAction'}]
                                            }]
                                        }]

    flow_defi_revse = [{'flow-definitions': [{'name': 'my_new_flow',
                                              'queue': 'hello_task',
                                              'sampling': {'name': 'constant', 'args': {'retry': 10}},
                                              'edges': [{'from': '', 'to': 'CheckMessage'},
                                                        {'from': 'CheckMessage', 'to': 'MessageLength'},
                                                        {'from': 'MessageLength', 'to': 'SuccessAction', 
                                                         'condition': {'and': [{'name': 'fieldEqual',
                                                                               'args': {'key': 'status',
                                                                                        'value': True}},
                                                                               {'name': 'fieldEqual',
                                                                               'args': {'key': 'checkvalue',
                                                                                        'value': True}},
                                                                               {'name': 'fieldEqual',
                                                                                'args': {'key': 'length',
                                                                                        'value': True}}]}},
                                                        {'from': 'MessageLength', 'to': 'FailureAction',
                                                         'condition': {'name': 'fieldEqual',
                                                                       'args': {'key': 'status', 'value': False}}}]
                                            }]
                                        }]


    Config.set_config_dict(node_dict, flow_defi_revse)
    Config.set_celery_app(app)
    dispatcher_id = run_flow('my_new_flow', Config.task_queues)
    
    return JsonResponse({'status': 'success'})` 

and got below trace in Celery process 

'[2018-11-21 04:09:52,753: INFO/MainProcess] celery@th1732u ready.
[2018-11-21 04:10:02,887: INFO/MainProcess] Received task: selinon.Dispatcher[29466ed5-9199-47e4-b5c3-37ede2b05804] 
[2018-11-21 04:10:02,892: ERROR/ForkPoolWorker-1] Task selinon.Dispatcher[29466ed5-9199-47e4-b5c3-37ede2b05804] raised unexpected: KeyError('my_new_flow',)
Traceback (most recent call last):
File "/home/user/anaconda3/envs/dmenv/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
R = retval = fun(*args, **kwargs)
File "/home/user/anaconda3/envs/dmenv/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
return self.run(*args, **kwargs)
File "/home/user/anaconda3/envs/dmenv/lib/python3.6/site-packages/selinon/dispatcher.py", line 173, in run
'queue': Config.dispatcher_queues[flow_name],
KeyError: 'my_new_flow''

Our understanding is dispatcher_queues which are discovered before run_flow call is not available in Celery process 

Thanks,
Rathish

**Comment by fridex** [comment]
Hi Rathish,

I haven't spotted anything suspicious in the provided example (is ``flow_definition`` variable unused intentionally?).

There looks like to be an issue with initialization of Selinon - the configuration class which keeps track of Selinon configuration has no queue name assigned for flow ``my_new_flow`` (which should be ``hello_task`` based on configuration).. Can you try to use ``set_config_yaml`` and load configuration from filesystem instead of ``set_config_dict`` to see if the issue persists?

**Comment by fridex** [comment]
Verification of configuration issues the following warning:

```console
> $ pipenv run selinon-cli inspect -n nodes.yaml -f flows.yaml                 
22096: [06:58:43] selinon.system _setup_nodes:1067: Unknown configuration keys in the nodes definitions, will be skipped: ['migration_dir']
Your configuration looks OK.
```

Configuration ``migrations_dir`` should be part of global section. But that shouldn't have anything to do with the issue you reported.

**Comment by rathish** [comment]
Hi Fridex,

Thanks for quick response, if we run the same in the code in the django initialised celery.py , then we are able to execute the flow without any issues. Only when we execute the run_flow via API / Function then we seeing Celery process is not getting the Configuration. Hope below further details will help to investigate further.

1. We have huge Django based project, in which Celery Worker does non-Selinon tasks as well. We are starting one another celery worker specific to selinon as below

`celery -A <django project name> worker -l info -Q <queue for selinon>& `

2. We run the project locally using the typical Django runserver command 

3. If the above provided  code loaded in the celery.py which will be initialized along with Celery app then flow is getting executed with out issue and configuration are transported

4. When we trigger the flow execution from API/Function we  get the trace which says Configuration is not loaded. 

since Config use class attributes / class functions which causing this issue ?

Thanks,
Rathish

**Comment by fridex** [comment]
> 4. When we trigger the flow execution from API/Function we get the trace which says Configuration is not loaded.

The first thing that came to my mind when reading this - where are you initializing Selinon? If the API server runs multiple worker processes to serve HTTP requests with running Selinon flows, each worker process has to have Selinon initialized.

**Comment by rathish** [comment]
Hi Fridex,

Our idea is to initialize Selinon in Django startup itself (only the app initialization).

project/celery.py

`from __future__ import absolute_import, unicode_literals
import os
from celery import Celery
from selinon import Config

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'projectname.settings')
app = Celery('projectname')
app.config_from_object('django.conf:settings', namespace='CELERY')
app.autodiscover_tasks()
Config.set_celery_app(app)
`

not loading the flow configurations during the start-up , so Selinon instance available for all spawned process. 

But the flow and nodes are initialized dynamically later in the API.  We are loading the flow on-demand or lazy loading via dict. 

Thanks,
Rathish

**Comment by fridex** [comment]
Selinon needs to register Selinon specific tasks (``Dispatcher`` and ``SelinonTaskEnvelope``) to Celery. Otherwise Celery does not have notion about these tasks.

> But the flow and nodes are initialized dynamically later in the API. We are loading the flow on-demand or lazy loading via dict.

My understanding is, that you are creating flow dynamically? It's not statically set on the application startup, am I right?

**Comment by rathish** [comment]
Hi Fridex,

>>Selinon needs to register Selinon specific tasks (Dispatcher and SelinonTaskEnvelope) to Celery. Otherwise Celery does not have notion about these tasks.

Yes, we are seeing these tasks in the Celery start-up


>>My understanding is, that you are creating flow dynamically? It's not statically set on the application startup, am I right?

yes, we are creating flow dynamically and yes it is not available on the application startup.  

Attached [selinon_demo.zip](https://github.com/selinon/selinon/files/2603056/selinon_demo.zip) quick application explaining our intention.

Thanks,
Rathish

**Comment by fridex** [comment]
> Not sure whether it is feasible?

This will require larger code changes. I don't have currently time for that. But patches are always welcome.

**Comment by rathish** [comment]
I understand, can we raise pull request ?

**Comment by fridex** [comment]
Sure, I'm open to any enhancements.

**Comment by fridex** [comment]
Let me know if I can help you with anything.

Just to give pointers - basically the patch would include configuration to be passed onto queue and accepted by the dispatcher task (see https://github.com/selinon/selinon/blob/master/selinon/dispatcher.py#L187). The configuration would be passed alongside flow parameters each time (on every dispatcher retry). The configuration of dispatcher would need to be updated on every dispatcher run (so possibly instantiate it on every dispatcher task run with  configuration).

**Comment by rathish** [comment]
Hi Fridex,

Thanks very much for your suggestion, we have tried following options and all didn't help.

1. We tried to pass the Config object between the Tasks (Dispatcher, TaskEnvlope, etc.) but target_class attribute is not JSON serializable , Kombu throws error while initialization. 

2. Lazy registration of Selinon Tasks after the configuration loading, but Celery didn't recognized the tasks. 

3. We tried to pass limited configuration between the tasks, that time some other functionalities failed because of missing parameters.

4. We tried to change apply_async to apply (sync) , that time configuration are transferred between the tasks, but Celery result related issues raised. 

We understood following from our experiments,

- Config needs to be available before the task discovery / initialization
- We cant do lazy task registration 
- Flow execution highly depends on the Async Results 

Considering all our understanding, we are planning to do Task Middle-ware design to cache the config, please review our plan, below.

1. We are planning to give Mixin in the Configuration like below,

`Class ConfigStoreMixin:
       def store_configuration(self, config, flow_name):
               pass

       def fetch_configuration(self, flow_name):
              from .config import Config
              return Config`

will be extended to pickle the configuration object in the database (custom implementation for our usecase). 

`class ConfigurationPickleModel(models.Model):
    flow_name = models.CharField()
    configuration_pickleobject = PickleObjectField()
    
    @classmethod
    def save_conf(self,flow_name, object):
        ConfigurationPickleModel.objects.create(flow_name=flow_name, configuration_pickleobject=object)
    
    @classmethod
    def get_conf(self,flow_name):
        return ConfigurationPickleModel.objects.get(flow_name=flow_name).configuration_pickleobject
        
class ConfigurationPickle(ConfigStoreMixin):
    def store_configuration(self, config, flow_name):
        pconfig = pickle.dump(config)
        ConfigurationPickleModel.save_conf(flow_name, pconfig)
        
    def fetch_configuration(self, flow_name):
        return pickle.loads(ConfigurationPickleModel.get_conf(flow_name))`

2. Update Configuration class with Configuration Store Object

 #.. from selinon..
 `class Config:
      ....
      ....
      config_store = None 

      @classmethod
      def set_config_store(self, config_store):
          self.config_store = config_store`
          
          
3. When the Celery loaded 

  `...
   Config.set_config_store(ConfigurationPickle())
   Config.set_celery_app(app)
   ...` 
   
4. Extend Dispatcher and TaskEnvolpe tasks with Base task, like below

`Class Configuration(Task):
         @classmethod
         def get_config(self, flow_name):
            from .config import Config
            if Config.config_store:
                return Config.config_store.fetch_configuration(flow_name)
            else:
                return Config
          `   

5. Modify Dispatcher Task and SelinonTaskEnvlope class to fetch configuration from the `self.get_config(flow_name)`

6. Before run_flow execution , we will update the `Config.config_store` with the current flows configuration.

Hope this changes wont affect the current functionalities of Selinon, please share your view.

Thanks,
Rathish

**Comment by fridex** [comment]
> We want to handle the config cache via Mixin extension , in our case of implementation plan to cache it in database to handle repeated flow execution scenario. If future someone want to implement the config cache in the Redis kind of store then it is possible to extend. Default it will return the current Config class.

Please note that this solution is highly dependent on your use case and is not that generic enough to be included in a library.

**Comment by rathish** [comment]
Agreed, we are trying out suggestion you have provided. There are some initial success, but we are not able execute two different flows with different configuration in parallel. Trying with proper examples. I will keep you posted.

**Comment by fridex** [comment]
> There are some initial success, but we are not able execute two different flows with different configuration in parallel.

This could be somehow limitation of the design where a class is used for storing configuration. Have you tried to rewrite the Config class so that it is instantiated as an object with the configuration passed as a dict so each worker has its own configuration instance?

**Comment by rathish** [comment]
Hi Fridex,

Few of the files method signature has changes and following are the changes, with these changes we are able to get success.

1. run.py - additional parameters are node definition and flow definition

From: `def run_flow(flow_name, node_args=None):`
To: `def run_flow(flow_name, node_args=None, nodes_definition={}, flow_definitions={}):`

 2. dispatcher.py - additional parameter is config

From: `def run(self, flow_name, node_args=None, parent=None, retried_count=None, retry=None,
state=None, selective=False, migration_version=None):`

To: `def run(self, flow_name, node_args=None, parent=None, retried_count=None, retry=None,
state=None, selective=False, migration_version=None, `config=None,):`

3. task_envelope.py - additional parameter is config

From: `def run(self, task_name, flow_name, parent, node_args, dispatcher_id, retried_count=None):`
To: `def run(self, task_name, flow_name, parent, node_args, dispatcher_id, retried_count=None, config=None):`
 
4. config.py:

 A new class method is defines `_update_config`

 5. system_state.py - additional parameter is config during initialization

From: `def __init__(self, dispatcher_id, flow_name, node_args=None, retry=None, state=None, parent=None, selective=None):`

To: `def __init__(self, dispatcher_id, flow_name, node_args=None, retry=None, state=None, parent=None, selective=None, config=None):`

- and passing the config under kwargs

We have attached all modified 5 files, if you are fine with the changes and implementation we will raise a pull request [selinon_lib_changes.tar.gz](https://github.com/selinon/selinon/files/2625612/selinon_lib_changes.tar.gz)

Thanks,
Rathish

**Comment by fridex** [comment]
Hi Rathish,

excellent! Nice work. Feel free to open a PR in author names. It will be easier for both ends to do a review, test and include changes in the code base.

Nice work!
F.
