### ISSUE TITLE
Failure Fallback task loses parent information

### ISSUE THREAD

**Issue by hyoungopb** [selinon/selinon#151]
## Issue description:
I have a fairly simple flow definition. In my create_draft_episode task, I raise a FatalTaskError, which triggers the fallback and gets inside fallback_task, but that task loses all knowledge of its parent. I can't figure out if I have a problem with my storage setup. We're using redis or if this is the expected behavior of the fallback.

### Expected behavior:
in fallback_task, the parent should be the previous task (create_draft_episode).

### Actual behavior:
parent = None / null

### Links to logs:

`[2020-01-06 07:49:55,847: WARNING/ForkPoolWorker-1] SELINON HYOUNG02.local - TASK_FAILURE : {"details": {"dispatcher_id": "292cfc82-0ff2-4871-94cc-a250c9f2c6fc", "flow_name": "spreakerPublish", "node_args": {"title_id": "610063"}, "parent": {"translate_dalet_to_spreaker": "fd0c316e-14db-4acf-8f23-f19f5fb0ec32"}, "queue": "celery-spreaker", "retried_count": 0, "task_id": "b82dc2b5-7cdf-4e70-b2af-adddaf544a58", "task_name": "create_draft_episode", "what": "Traceback (most recent call last):\n  File \"/Users/hyoung/workspace/content_gateway/spreaker-celery-demo/venv/lib/python3.6/site-packages/selinon/task_envelope.py\", line 114, in run\n    result = task.run(node_args)\n  File \"/Users/hyoung/workspace/content_gateway/spreaker-celery-demo/workflows/spreaker/tasks.py\", line 85, in run\n    raise FatalTaskError\nselinon.errors.FatalTaskError\n"}, "event": "TASK_FAILURE", "time": "2020-01-06 15:49:55.847314"}
[2020-01-06 07:49:55,849: WARNING/ForkPoolWorker-1] SELINON HYOUNG02.local - STORAGE_OMIT_STORE_ERROR : {"details": {"error_traceback": "  File \"/Users/hyoung/workspace/content_gateway/spreaker-celery-demo/venv/lib/python3.6/site-packages/selinon/task_envelope.py\", line 114, in run\n    result = task.run(node_args)\n  File \"/Users/hyoung/workspace/content_gateway/spreaker-celery-demo/workflows/spreaker/tasks.py\", line 85, in run\n    raise FatalTaskError\n", "error_type": "<class 'selinon.errors.FatalTaskError'>", "error_value": "", "flow_name": "spreakerPublish", "node_args": {"title_id": "610063"}, "task_id": "b82dc2b5-7cdf-4e70-b2af-adddaf544a58", "task_name": "create_draft_episode"}, "event": "STORAGE_OMIT_STORE_ERROR", "time": "2020-01-06 15:49:55.849046"}
[2020-01-06 07:49:55,857: ERROR/ForkPoolWorker-1] Task selinon.SelinonTaskEnvelope[b82dc2b5-7cdf-4e70-b2af-adddaf544a58] raised unexpected: FatalTaskError()
Traceback (most recent call last):
  File "/Users/hyoung/workspace/content_gateway/spreaker-celery-demo/venv/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/hyoung/workspace/content_gateway/spreaker-celery-demo/venv/lib/python3.6/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/hyoung/workspace/content_gateway/spreaker-celery-demo/venv/lib/python3.6/site-packages/selinon/task_envelope.py", line 169, in run
    raise self.retry(max_retries=0, exc=exc)
  File "/Users/hyoung/workspace/content_gateway/spreaker-celery-demo/venv/lib/python3.6/site-packages/celery/app/task.py", line 703, in retry
    raise_with_context(exc)
  File "/Users/hyoung/workspace/content_gateway/spreaker-celery-demo/venv/lib/python3.6/site-packages/selinon/task_envelope.py", line 114, in run
    result = task.run(node_args)
  File "/Users/hyoung/workspace/content_gateway/spreaker-celery-demo/workflows/spreaker/tasks.py", line 85, in run
    raise FatalTaskError
selinon.errors.FatalTaskError
[2020-01-06 07:50:03,368: INFO/ForkPoolWorker-2] SELINON HYOUNG02.local - DISPATCHER_WAKEUP : {"details": {"dispatcher_id": "292cfc82-0ff2-4871-94cc-a250c9f2c6fc", "flow_name": "spreakerPublish", "migration_version": 0, "node_args": {"title_id": "610063"}, "parent": null, "queue": "celery-spreaker", "retried_count": 0, "retry": 8, "selective": false, "state": {"active_nodes": [{"id": "b82dc2b5-7cdf-4e70-b2af-adddaf544a58", "name": "create_draft_episode"}], "failed_nodes": {}, "finished_nodes": {"query_dalet": ["e7914179-cbb7-4994-98c7-8254d965b641"], "translate_dalet_to_spreaker": ["fd0c316e-14db-4acf-8f23-f19f5fb0ec32"]}, "triggered_edges": [0, 1, 2], "waiting_edges": [1, 2]}}, "event": "DISPATCHER_WAKEUP", "time": "2020-01-06 15:50:03.367888"}
`

### Selinon & Celery version:

Running `selinon-cli version` gave me:

Celery version: 4.3.0

### Links to YAML config files:
nodes.yml
`---
  tasks:
    - name: 'query_dalet'
      classname: 'QueryDalet'
      import: 'tasks'
      storage: 'Redis'
      max_retry: 5

    - name: 'translate_dalet_to_spreaker'
      classname: 'TranslateDaletToSpreaker'
      import: 'tasks'
      storage: 'Redis'
      max_retry: 5

    - name: 'create_draft_episode'
      classname: 'CreateDraftEpisode'
      import: 'tasks'
      storage: 'Redis'
      max_retry: 5

    - name: 'upload_audio_to_spreaker'
      classname: 'UploadAudioToSpreaker'
      import: 'tasks'
      storage: Redis
      max_retry: 5

    - name: 'check_episode_status'
      classname: 'CheckEpisodeStatus'
      import: 'tasks'
      storage: Redis
      max_retry: 6
      retry_countdown: 10

    - name: 'publish_episode'
      classname: 'PublishEpisode'
      import: 'tasks'
      storage: Redis
      max_retry: 5

    - name: 'complete_notification'
      classname: 'CompleteNotification'
      import: 'tasks'
      storage: Redis
      max_retry: 5

    - name: 'fallback_task'
      classname: 'FallbackTask'
      import: 'tasks'
      storage: Redis
      max_retry: 1

  flows:
    - spreakerPublish

  storages:
    - name: 'Redis'
      classname: 'Redis'
      import: 'selinon.storages.redis'
      configuration:
        host: "{REDIS_HOST}"
        port: "{REDIS_PORT}"
        db: 0
        charset: 'utf-8'
        password: "{REDIS_PASSWORD}"

  global:
    default_task_queue: 'celery-spreaker'
    default_dispatcher_queue: 'celery-spreaker'
    trace:
      - logging: true`

flow.yml
`---
  flow-definitions:
    # Publish audio episode to Spreaker
    - name: 'spreakerPublish'
      queue: 'celery-spreaker'
      propagate_parent: true
      propagate_node_args: true
      propagate_compound_finished: true
      edges:
        - from:
          to: 'query_dalet'
        - from: 'query_dalet'
          to: 'translate_dalet_to_spreaker'
        - from: 'translate_dalet_to_spreaker'
          to: 'create_draft_episode'
        - from: 'create_draft_episode'
          to: 'upload_audio_to_spreaker'
        - from: 'upload_audio_to_spreaker'
          to: 'check_episode_status'
        - from: 'check_episode_status'
          to: 'publish_episode'
        - from: 'publish_episode'
          to: 'complete_notification'

      failures:
        # failures have to be list individual nodes https://github.com/selinon/selinon/blob/master/selinon/failure_node.py
        - nodes:
            - 'create_draft_episode'
          fallback:
            - 'fallback_task'
`

celeryconfig.py

`import os
from kombu import Exchange, Queue

task_queues = (
    Queue('celery-spreaker', Exchange('celery-spreaker'), routing_key='celery-spreaker'),
)

task_default_queue = 'celery-spreaker'
result_backend = os.getenv('RESULT_BACKEND', 'redis://localhost:6379/0')
broker_url = os.getenv('AMQP_URI', 'pyamqp://guest@localhost/')
`
worker.py
`from selinon import Config, run_flow
from celery import Celery

app = Celery('spreakerPublish')
app.config_from_object('celeryconfig')
Config.set_config_yaml('./nodes.yml', ['./flow.yml', ])
Config.set_celery_app(app)

@app.task
def run_spreaker_publish(title_id):
    dispatcher_id = run_flow('spreakerPublish', node_args={'title_id': str(title_id)})
    print("dispatcher ID = {}".format(dispatcher_id))`

call.py
`TITLE_ID = 610063

connection = pika.BlockingConnection(pika.ConnectionParameters(host='localhost', port=5672, virtual_host='/'))
channel = connection.channel()

channel.queue_declare(queue='celery-spreaker', durable=True)

id = str(uuid.uuid4())
body = {
    'id': id,
    'task': 'worker.run_spreaker_publish',
    'function': '',
    'args': (TITLE_ID,)
}

properties = pika.BasicProperties(correlation_id=id,
                                  content_type="application/json",
                                  content_encoding="UTF-8")

print("Triggering Spreaker workflow...", end='')
channel.basic_publish(exchange='', routing_key='celery-spreaker', properties=properties, body=json.dumps(body))
connection.close()
print("done.")`

### Links to task implementations:
tasks.py
`import os
from abc import ABC

from selinon import SelinonTask
from selinon.errors import Retry, FatalTaskError
from nameko.standalone.rpc import ClusterRpcProxy

config = {
    'AMQP_URI': os.getenv('AMQP_URI', 'pyamqp://guest:guest@localhost')
}

class LookbackTask(SelinonTask, ABC):
    """ Extends SelinonTask, adding method for getting results from previous task.
    TODO (rvincent): this is a hack!  Find the proper way with Selinon.
    """
    def get_task_results(self):
        """  Pulls the first parent name from the list and queries for results from that parent task. """
        parent_name = list(self.parent.keys())[0]
        results = self.parent_task_result(parent_name)
        if results:
            return results
        return {}

    task_results = property(get_task_results)

class QueryDalet(SelinonTask):
    """ Pulls metadata from Dalet given a Title ID. """
    def run(self, node_args):
        with ClusterRpcProxy(config) as cluster_rpc:
            status, response = cluster_rpc.dalet_service.fetch_by_id(int(node_args['title_id']))
            if status == 'error':
                print("response = {}".format(response))
                raise Retry(countdown=2)
                # raise FatalTaskError

            results = {
                'status': status,
                'dalet_metadata': response,
                'file_name': '/content-store/{}.mp3'.format(response['TitleId'])
            }
            if os.environ.get('LOCAL_RUN', False):
                results['file_name'] = '../../content-store/test.mp3'

            return results

class TranslateDaletToSpreaker(LookbackTask):
    """ Translates Dalet metadata into Spreaker metadata.
    """
    def run(self, node_args):
        results = self.task_results
        # not loading results from previous step, this step just processes the Dalet metadata
        with ClusterRpcProxy(config) as cluster_rpc:
            status, metadata = cluster_rpc.spreaker_service.translate_dalet_to_spreaker(results['dalet_metadata'])

            # parse and process the activity log
            # TODO (rvincent): should we specify the platform?
            activity_log = cluster_rpc.dalet_service.parse_activity_log(metadata)

            results.update({
                'status': status,
                'metadata': metadata,
                'activity_log': activity_log
            })
            return results

class CreateDraftEpisode(LookbackTask):
    """ Creates draft episode on Spreaker. A draft episode is: unpublished and does not contain audio at this point """

    def run(self, node_args):
        results = self.task_results
        with ClusterRpcProxy(config) as cluster_rpc:
            status, episode_id = cluster_rpc.spreaker_service.create_draft_episode(self.task_results['metadata'])

            results.update({
                'episode_id': episode_id,
                'status': status,
            })
            if status == 'error':
                raise FatalTaskError

        return results

class UploadAudioToSpreaker(LookbackTask):
    """ Uploads audio file to an existing Spreaker draft episode. """

    def run(self, node_args):
        print('inside UploadAudioToSpreaker')
        results = self.task_results
        with ClusterRpcProxy(config) as cluster_rpc:
            status, response = cluster_rpc.spreaker_service.upload_audio_to_spreaker(results['episode_id'],
                                                                                     self.task_results['file_name'])
            results.update({'status': status})

            print(status, response)

        return results

class CheckEpisodeStatus(LookbackTask):
    """ Waits until the episode audio is ready for playback.
        This prevents a user from finding a published episode with a broken player. Higher risk for longer episodes.
    """

    def run(self, node_args):
        print("inside CheckEpisodeStatus")
        results = self.task_results
        with ClusterRpcProxy(config) as cluster_rpc:
            status, site_url = cluster_rpc.spreaker_service.check_encode_status(results['episode_id'])
            if not status or status == 'warning':
                raise Retry(countdown=2)

            results.update({'status': status, 'site_url': site_url})

        return results

class PublishEpisode(LookbackTask):
    """ Publishes the draft episode. """

    def run(self, node_args):
        print("inside PublishEpisode")
        results = self.task_results
        with ClusterRpcProxy(config) as cluster_rpc:
            status, response = cluster_rpc.spreaker_service.publish_episode(results['episode_id'])
            if not status or status == 'warning':
                raise Retry(countdown=2)

            results.update({'status': status})

        return results

class CompleteNotification(LookbackTask):
    """ Sends the final notifications. """

    def run(self, node_args):
        print("inside CompleteNotification")
        results = self.task_results
        with ClusterRpcProxy(config) as cluster_rpc:
            # update history
            cluster_rpc.dalet_service.update_history(int(node_args['title_id']), 'Published to Spreaker')

            # update activity log
            cluster_rpc.dalet_service.update_activity_log(int(node_args['title_id']),
                                                              platform='Spreaker',
                                                              platform_id=results['episode_id'],
                                                              activity='published',
                                                              result='success')
        return results

class FallbackTask(SelinonTask, ABC):
    print('in fallback task')
    def run(self, node_args):
        print('1234')

        return True

`

**Comment by fridex** [comment]
As of now, the fallback node is run always with `parent=None`:

https://github.com/selinon/selinon/blob/33dede9d3bee667365279b4f6b0101c3e6c88fd3/selinon/system_state.py#L526-L528

**Comment by fridex** [comment]
The logic for retrieving exception is already present:

https://github.com/selinon/selinon/blob/master/selinon/selinon_task.py#L108-L125

I think I forgot to implement the parent propagation functionality.

**Comment by hyoungopb** [comment]
Thanks for your responses. My team is debating forking this project to make it meet our needs. We see you haven't developed on this in a while. What is the likelihood you are going to be updating this project.

**Comment by fridex** [comment]
> Thanks for your responses. My team is debating forking this project to make it meet our needs. We see you haven't developed on this in a while. What is the likelihood you are going to be updating this project.

Unfortunately, I don't have spare time to work on this now. However, I'm open to assist and/or help with any extensions to this project - if you send PRs, I'm happy to review them.

**Comment by hyoungopb** [comment]
thank you!
