### ISSUE TITLE
Trace logging failing due to AsyncResult not serializable

### ISSUE THREAD

**Issue by Lyalpha** [selinon/selinon#153]
More generally, I am trying to see if using `selinon` if for my needs, but I am finding it somewhat difficult. I notice a lack of recent activity, is the package still active/maintained or is it considered stable and left alone now?

## Issue description:
When trying to use `logging: true`, I get a `TypeError: Object of type AsyncResult is not JSON serializable`

### Steps to reproduce:
With files:
```
# seltest/tasks.py
from selinon import SelinonTask


class Task1(SelinonTask):
    def run(self, node_args):
        return node_args


class Task2(SelinonTask):
    def run(self, node_args):
        return node_args
```
```
# seltest/celery_worker.py
from selinon import Config
from celery import Celery

celery_app = Celery(
    "seltest",
    backend='db+sqlite:///results.db',
    broker='amqp://guest:guest@localhost:5672//'
)

Config.set_celery_app(celery_app)
Config.set_config_yaml('selinon_config/nodes.yaml', ['selinon_config/flow1.yaml'])
```
```
# run.py
from selinon import run_flow
from seltest.celery_worker import Config

dispatcher_id = run_flow('flow1', {'foo': 'bar'})
```
```
# selinon_config/flow1.yaml
---
  flow-definitions:
    - name: 'flow1'
      edges:
          - from:
            to:
              - 'Task1'
          - from:
              - 'Task1'
            to:
              - 'Task2'
```
```
# selinon_config/nodes.yaml
---
tasks:
  - name: 'Task1'
    import: 'seltest.tasks'
    storage: 'Storage1'

  - name: 'Task2'
    import: 'seltest.tasks'
    storage: 'Storage1'

flows:
  - 'flow1'

storages:
  - name: 'Storage1'
    classname: 'PostgreSQL'
    import: 'selinon.storages.postgresql'
    configuration:
      connection_string: 'postgres://dbuser:secretpassword@localhost:5432/kadmilos_tasks'
      encoding: 'utf-8'

global:
  trace:
    - logging: true
```
* Start celery worker via: `celery worker -A seltest.celery_worker -l info`
* Run program via: `python -m run`

### Expected behavior:

Python logging

### Actual behavior:

```
Failed to report to trace function <bound method Trace.logging_trace_func of <class 'selinon.trace.Trace'>>: Object of type AsyncResult is not JSON serializable
Traceback (most recent call last):
  File "/home/jdl/.virtualenvs/selinon_test/lib/python3.8/site-packages/selinon/trace.py", line 395, in log
    trace_func(event, to_report)
  File "/home/jdl/.virtualenvs/selinon_test/lib/python3.8/site-packages/selinon/trace.py", line 423, in logging_trace_func
    % (platform.node(), cls.event2str(event), json.dumps(report_dict, sort_keys=True))
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type AsyncResult is not JSON serializable
```

### Links to logs:

.

### Are you able to reproduce the issue with `selinon-cli execute`?

Get an (unrelated?) `AttributeError`: 
```
selinon-cli execute --flow-name flow1 -n selinon_config/nodes.yaml -f selinon_config/flow1.yaml 
Traceback (most recent call last):
  File "/home/jdl/.virtualenvs/selinon_test/bin/selinon-cli", line 10, in <module>
    sys.exit(cli())
  File "/home/jdl/.virtualenvs/selinon_test/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/jdl/.virtualenvs/selinon_test/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/jdl/.virtualenvs/selinon_test/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jdl/.virtualenvs/selinon_test/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jdl/.virtualenvs/selinon_test/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jdl/.virtualenvs/selinon_test/lib/python3.8/site-packages/selinon/cli.py", line 189, in execute
    executor.run(flow_name, node_args)
  File "/home/jdl/.virtualenvs/selinon_test/lib/python3.8/site-packages/selinon/executor/executor.py", line 108, in run
    run_flow(flow_name, node_args)
  File "/home/jdl/.virtualenvs/selinon_test/lib/python3.8/site-packages/selinon/run.py", line 47, in run_flow
    return _do_run_flow(kwargs, queue)
  File "/home/jdl/.virtualenvs/selinon_test/lib/python3.8/site-packages/selinon/run.py", line 22, in _do_run_flow
    dispatcher_id = Dispatcher().apply_async(kwargs=kwargs, queue=queue)
  File "/home/jdl/.virtualenvs/selinon_test/lib/python3.8/site-packages/selinon/executor/celery_mocks.py", line 113, in simulate_apply_async
    instance.request = SimulateRequest(instance)
AttributeError: can't set attribute
```

### Selinon & Celery version:

Running `selinon-cli version` gave me:
Selinon version: 1.1.0
Celery version: 4.4.2

- [X] I have tried the latest master but the issue still pesists:
  `pip3 install --force-reinstall git+https://github.com/selinon/selinon@master`

### Links to YAML config files:

See above

### Links to task implementations:

See above

**Comment by fridex** [comment]
hi @Lyalpha,

> I notice a lack of recent activity, is the package still active/maintained or is it considered stable and left alone now?

It's more like free time activity for me - I didn't find much time to extend/work on this project. It is still running in few prod deployments where it is considered stable enough for their use cases.

I'll try to find time and have a look at this issue. Thanks for the report.
