### ISSUE TITLE
cannot find task module 

### ISSUE THREAD

**Issue by SamaiMed** [selinon/selinon#154]
## Issue description:
hi im trying to execute a simple hello world selinon task, but i keep getting this error
 `
16012: [03:04:44] cli.py _expand_flow_definitions:90: Found flow configuration file 'seli_worker\\config\\flows\\hello.yaml'
16012: [03:04:44] selinon.system from_files:1152: Parsing 'seli_worker\config\nodes.yaml'
16012: [03:04:44] selinon.task __init__:69: Creating task with name 'HelloTask' import path 'seli_worker.tasks', class name 'HelloTask'
16012: [03:04:44] selinon.flow __init__:36: Creating flow 'hello'
16012: [03:04:44] selinon.system from_files:1166: Parsing 'seli_worker\config\flows\hello.yaml'
16012: [03:04:44] selinon.system _post_parse_check:809: Post parse check is going to be executed
16012: [03:04:44] selinon.system _check:930: Checking system consistency
16012: [03:04:44] selinon.config set_config_yaml:144: Generating config.py file to created temporary file 'C:\Users\Fatboy\AppData\Local\Temp\tmp6cwd_pnj'
16012: [03:04:44] selinon.config set_config_py:127: Using config.py file from 'C:\Users\Fatboy\AppData\Local\Temp\tmp6cwd_pnj'
Traceback (most recent call last):
  File "c:\users\fatboy\appdata\local\continuum\miniconda3\envs\cst\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\fatboy\appdata\local\continuum\miniconda3\envs\cst\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Fatboy\AppData\Local\Continuum\miniconda3\envs\cst\Scripts\selinon-cli.exe\__main__.py", line 7, in <module>
  File "c:\users\fatboy\appdata\local\continuum\miniconda3\envs\cst\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\fatboy\appdata\local\continuum\miniconda3\envs\cst\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\fatboy\appdata\local\continuum\miniconda3\envs\cst\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\fatboy\appdata\local\continuum\miniconda3\envs\cst\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\fatboy\appdata\local\continuum\miniconda3\envs\cst\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\fatboy\appdata\local\continuum\miniconda3\envs\cst\lib\site-packages\selinon\cli.py", line 170, in execute
    executor = Executor(nodes_definition, flow_definitions,
  File "c:\users\fatboy\appdata\local\continuum\miniconda3\envs\cst\lib\site-packages\selinon\executor\executor.py", line 81, in __init__
    Config.set_config_yaml(nodes_definition, flow_definitions,
  File "c:\users\fatboy\appdata\local\continuum\miniconda3\envs\cst\lib\site-packages\selinon\config.py", line 153, in set_config_yaml
    cls.set_config_py(config_py)
  File "c:\users\fatboy\appdata\local\continuum\miniconda3\envs\cst\lib\site-packages\selinon\config.py", line 128, in set_config_py
    config_module = runpy.run_path(config_code)
  File "c:\users\fatboy\appdata\local\continuum\miniconda3\envs\cst\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "c:\users\fatboy\appdata\local\continuum\miniconda3\envs\cst\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\users\fatboy\appdata\local\continuum\miniconda3\envs\cst\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Fatboy\AppData\Local\Temp\tmp6cwd_pnj", line 4, in <module>
    from seli_worker.tasks import HelloTask as HelloTask
ModuleNotFoundError: No module named 'seli_worker'
`

### Steps to reproduce:
my project is structure as follows 
.
├── app.py
├── entrypoint.py
├── run.py
└── seli_worker
    ├── __init__.py
    ├── config
    │   ├── flows
    │   │   └── hello.yaml
    │   └── nodes.yaml
    ├── tasks
    │   ├── __init__.py
    │   └── hello.py
    └── utils.py

and i execute the flow with selinon-cli
`selinon-cli -vvv execute --flow-name hello --nodes-definition seli_worker\config\nodes.yaml --flow-definitions seli_worker\config\flows`

### Selinon & Celery version:
celery version 5.0.2 (singularity)
silinon version 1.1.0

### Links to project files:
the YAML files are in config
the entire project is in << https://drive.google.com/drive/folders/17xko9t3sf4ao6T4qe4SQ0jgW2T16ijpT?usp=sharing >>

**Comment by fridex** [comment]
Hi @SamaiMed,

it looks like the code is not on your PYTHONPATH. Make sure this code runs correctly:

```python
from seli_worker.tasks import HelloTask as HelloTask
```

I would expect something like this would work (but you use windows, so not sure about the solution):

```
PYTHONPATH=. selinon-cli -vvv execute --flow-name hello --nodes-definition seli_worker\config\nodes.yaml --flow-definitions seli_worker\config\flows
```
